// Curated pool of recognisable stations the daily-puzzle endpoint draw is
// biased towards: zone 1-2 hubs, interchanges, landmarks and termini. Matching
// is on the cleaned display name (lib/format displayName), mirroring the
// curated-facts override convention, so the list survives id changes in the
// TfL data. Names absent from a given graph are simply ignored.

/** Cleaned display names of recognisable endpoint stations. */
export const LANDMARK_NAMES: ReadonlySet<string> = new Set([
  // Zone 1 core
  "King's Cross St. Pancras",
  'Oxford Circus',
  'Piccadilly Circus',
  'Leicester Square',
  'Covent Garden',
  'Bank',
  'Liverpool Street',
  'Waterloo',
  'Victoria',
  'Paddington',
  'Baker Street',
  'Bond Street',
  'Tottenham Court Road',
  'Euston',
  'London Bridge',
  'Westminster',
  'Green Park',
  'Embankment',
  'Charing Cross',
  'Holborn',
  'Moorgate',
  'Farringdon',
  'Old Street',
  'Angel',
  'Blackfriars',
  'Temple',
  'Mansion House',
  'Cannon Street',
  'Monument',
  'Russell Square',
  'Goodge Street',
  'Warren Street',
  'Great Portland Street',
  'Mornington Crescent',
  "St. James's Park",
  "St. Paul's",
  'Barbican',
  'Aldgate',
  'Tower Hill',
  'Tower Gateway',
  'Marble Arch',
  'Edgware Road',
  'Marylebone',
  'Hyde Park Corner',
  "Regent's Park",
  'Knightsbridge',
  'Sloane Square',
  'South Kensington',
  'Gloucester Road',
  'High Street Kensington',
  'Bayswater',
  'Queensway',
  'Lancaster Gate',
  'Notting Hill Gate',
  'Holland Park',
  "Earl's Court",
  'Pimlico',
  'Vauxhall',
  'Elephant & Castle',
  'Borough',
  // East + Docklands
  'Whitechapel',
  'Bethnal Green',
  'Mile End',
  'Stratford',
  'Stratford International',
  'Canary Wharf',
  'North Greenwich',
  'Greenwich',
  'Cutty Sark',
  'Island Gardens',
  'Canada Water',
  'Bermondsey',
  'Surrey Quays',
  'New Cross',
  'Lewisham',
  'Woolwich',
  'Custom House',
  'Royal Victoria',
  'Canning Town',
  'West Ham',
  'East Ham',
  'Barking',
  'Shoreditch High Street',
  'Hoxton',
  'Dalston Junction',
  'Hackney Central',
  // North
  'Camden Town',
  'Kentish Town',
  'Hampstead',
  'Archway',
  'Highgate',
  'Highbury & Islington',
  'Finsbury Park',
  'Seven Sisters',
  'Walthamstow Central',
  'Finchley Road',
  'Swiss Cottage',
  "St. John's Wood",
  'West Hampstead',
  // West
  'Hammersmith',
  "Shepherd's Bush",
  'White City',
  'Wood Lane',
  'Ladbroke Grove',
  'Maida Vale',
  "Queen's Park",
  'Wembley Park',
  'Wembley Central',
  'Willesden Junction',
  'Ealing Broadway',
  'Acton Town',
  'Kensington',
  'Heathrow Terminals 2 & 3',
  // South
  'Brixton',
  'Oval',
  'Kennington',
  'Clapham Common',
  'Clapham Junction',
  'Balham',
  'Tooting Broadway',
  'Morden',
  'Wimbledon',
  'Putney Bridge',
  'Fulham Broadway',
  'Richmond',
  'Kew Gardens',
  'Battersea Power Station',
  'Nine Elms',
  'Peckham Rye',
  'Crystal Palace',
  'West Croydon',
])
