"""Curated fun facts for every station, keyed by display name.

Each station has one punchy, accurate sentence. The headline stations were
hand-authored; the rest were drafted and then adversarially fact-checked against
web sources. Matched via ``normalise_name`` on the cleaned display name in the
enrichment step, taking priority over any auto-derived Wikipedia fact. British
English, no em or en dashes.
"""

CURATED_FACTS: dict[str, str] = {
    "Abbey Road": "This West Ham stop is so often confused with the Beatles' St John's Wood crossing that TfL added a sign telling misdirected tourists they have reached the wrong Abbey Road.",
    "Abbey Wood": "The station takes its name from the wood beside Lesnes Abbey, founded in 1178 by Richard de Luci reputedly in penance for his part in the conflict that led to the murder of Thomas Becket, whose ruins lie a short walk away.",
    "Acton Central": "Acton was once nicknamed Soapsuds Island, with around 170 laundries clustered in South Acton by 1890, drawn there by the area's soft water.",
    "Acton Main Line": "It sits on Brunel's Great Western Main Line, an alignment so level and straight that supporters nicknamed it Brunel's billiard table.",
    "Acton Town": "The station was rebuilt in 1932 to a brick, concrete and glass design by Charles Holden, and is now a Grade II listed building.",
    "Aldgate": "Aldgate is reputedly built over a mass grave from the Great Plague of 1665.",
    "Aldgate East": "The station was shifted about 500 feet east overnight in 1938 by some 900 workmen, and its north-eastern entrance forms part of the Whitechapel Gallery building.",
    "All Saints": "It is named after the nearby All Saints church, the early-1820s parish church of Poplar, and its entrance faces Chrisp Street Market across the East India Dock Road.",
    "Alperton": "The name comes from Old English and means the farmstead of a man called Ealhbeorht, and the present brick, concrete and glass station was designed by Charles Holden around 1930.",
    "Amersham": "Amersham is the highest station above sea level (about 150 m) and tied for the furthest from central London.",
    "Anerley": "The name comes from a Scots word meaning solitary or only, after a house called Anerly built nearby by William Sanderson, a Scottish silk and wine merchant from Galashiels.",
    "Angel": "Angel has the longest escalator on the network, a 60 m climb.",
    "Archway": "Nearby at the foot of Highgate Hill stands the Whittington Stone, reputedly marking where Dick Whittington is said to have heard Bow bells call him back to become Lord Mayor of London.",
    "Arnos Grove": "Arnos Grove's circular Holden ticket hall is one of the most celebrated buildings on the Underground.",
    "Arsenal": "Renamed from Gillespie Road in 1932 at manager Herbert Chapman's urging, it is the only Underground station named directly after a football club.",
    "Baker Street": "Baker Street has more platforms than any other Tube station (ten) and was part of the world's first underground railway in 1863.",
    "Balham": "On 14 October 1940 a bomb cratered the road above and a bus toppled in, while the flooded tunnels drowned dozens of shelterers in one of the Blitz's worst Tube disasters.",
    "Bank": "Bank is named after the Bank of England, which it sits beneath.",
    "Barbican": "It takes its name from a barbican, a fortified outpost or watchtower of the kind that once stood by the old Roman and medieval city wall nearby.",
    "Barking": "The town grew around Barking Abbey, founded around 666 and by its dissolution in 1539 reputedly the third wealthiest nunnery in England.",
    "Barking Riverside": "This eastern terminus of the Suffragette line stands on the roughly 440-acre brownfield site of the former Barking Power Station and links to an Uber Boat by Thames Clippers pier.",
    "Barkingside": "Its grand Baroque station with a cupola was built to a high standard to serve Dr Barnardo's Girls' Village Home, and the Barnardo's charity remains headquartered nearby in Barkingside.",
    "Barons Court": "This 1905 station keeps high-backed wooden platform benches with the station name spelt out on enamelled panels along their backs, a feature found nowhere else on the Underground.",
    "Battersea Power Station": "This coal-fired landmark with four white chimneys featured on Pink Floyd's 1977 Animals cover, and during the December 1976 shoot the inflatable pig broke loose, drifted into Heathrow's flight path and grounded flights before landing on a Kent farm.",
    "Bayswater": "Just outside, the grand facades at 23 and 24 Leinster Gardens are dummies about five feet thick, built to hide the open railway cutting where early steam trains vented their fumes.",
    "Beckton": "Beckton honours gas-company governor Simon Adams Beck, whose works here opened in 1870 and grew into one of the largest gasworks in Europe.",
    "Beckton Park": "Set in a cutting beneath the centre of an elevated roundabout, the station sits by the north quay of the former Royal Albert Dock.",
    "Becontree": "It serves the Becontree estate, built between 1921 and 1935 as the largest public housing estate in the world, with around 26,000 homes.",
    "Belsize Park": "Beneath the station lies one of London's WW2 deep-level shelters, opened to the public in 1944 during the V1 flying-bomb campaign.",
    "Bermondsey": "Ian Ritchie's 1999 Jubilee line station was designed so that daylight passes down through the structure and reaches the deep platforms below.",
    "Bethnal Green": "On 3 March 1943 a crush on the shelter stairs here killed 173 people, believed to be the largest single loss of British civilian life of the Second World War, marked today by the Stairway to Heaven memorial.",
    "Blackfriars": "Its platforms span the Thames under a roof of around 4,400 solar panels, said to be the largest solar bridge in the world when completed in 2014.",
    "Blackhorse Road": "The name is thought to derive from Black House, a mansion that once stood on the road, and the station is marked by a black horse sculpture by David McFall.",
    "Blackwall": "From here in December 1606 the Susan Constant, Godspeed and Discovery set sail to found Jamestown, Virginia, the first permanent English colony in North America.",
    "Bond Street": "There is no road actually called Bond Street: the street splits into Old and New Bond Street, and the station's entrances are on Oxford Street and Hanover Square.",
    "Borough": "Borough opened in 1890 on the City & South London Railway, the world's first deep-level electric tube, with its entrance on Borough High Street at the corner of Marshalsea Road, named after the debtors' prison where Dickens's father was held.",
    "Boston Manor": "The station takes its name from Boston Manor House, a Grade I listed Jacobean mansion built in 1622 that still stands in its park a short walk away in Brentford.",
    "Bounds Green": "On 13 October 1940 a single bomb collapsed the westbound platform tunnel, killing sixteen shelterers at the scene, including three Belgian refugees, with a seventeenth dying later in hospital.",
    "Bow Church": "It is named after the central-reservation church of St Mary, outside which stands a Gladstone statue whose hands are repeatedly painted red, by tradition in protest at a rumour that Bryant and May matchworkers' wages helped pay for it.",
    "Bow Road": "Nearby on Fairfield Road stood the Bryant & May match factory, where the 1888 matchgirls' strike, supported by Annie Besant, won better pay and conditions.",
    "Brent Cross": "Opened in 1923 simply as 'Brent' after the nearby river, it was renamed in 1976 to serve Brent Cross, Britain's first stand-alone covered shopping centre.",
    "Brentwood": "The Essex town it serves is home to Brentwood School, founded in 1557 by Sir Antony Browne.",
    "Brixton": "Brixton is the southern end of the Victoria line, and one of its busiest stops.",
    "Brockley": "The nearby Brockley Jack pub, a historic coaching inn, is reputedly linked in local legend to highwaymen, though that tale may be later embroidery to drum up trade.",
    "Bromley-by-Bow": "It sits beside the River Lea near Three Mills, a historic tidal mill site reputedly recorded in the Domesday Book and now home to film and television studios.",
    "Brondesbury": "The name derives from Brand, a medieval prebendary, so Brondesbury means roughly Brand's manor, and the land long belonged to St Paul's Cathedral.",
    "Brondesbury Park": "The surrounding estate's grounds were landscaped by Humphry Repton, the celebrated Georgian designer, after Lady Salusbury bought the house in 1789, the subject of his very first Red Book.",
    "Bruce Grove": "It is named after nearby Bruce Castle, on land once held by the family of Robert the Bruce, who forfeited his English holdings on becoming King of Scots in 1306.",
    "Buckhurst Hill": "The railway's arrival in 1856 spurred rapid building that enclosed parts of Epping Forest, a practice halted by the 1878 act placing the forest under City of London protection.",
    "Burnham": "It is the gateway to Burnham Beeches, an ancient woodland of pollards averaging well over 400 years old that the City of London Corporation bought in 1880 to save from developers.",
    "Burnt Oak": "The name, first recorded in 1754, is said to come from a field whose ancient oak had reputedly been burned by lightning, beside the old Roman Watling Street, now the A5.",
    "Bush Hill Park": "Sir Hugh Myddelton, engineer of the New River that brought drinking water to London from 1613, lived at nearby Bush Hill House while overseeing the works.",
    "Bushey": "Nearby Bushey was home to Bushey Studios, founded by the painter Hubert von Herkomer in 1913 and the world's oldest operating film studio when it closed in 1985.",
    "Caledonian Road": "One of Leslie Green's 1906 stations clad in oxblood faience, it takes its name from the road built to serve the Royal Caledonian Asylum, a charity for the children of Scots.",
    "Caledonian Road & Barnsbury": "Caledonian Road took its name from the Caledonian Asylum, which moved to the road in 1828 to house children of Scottish servicemen who died or were disabled in the Napoleonic Wars.",
    "Cambridge Heath": "It is the nearest Overground stop to the Young V&A, the former Museum of Childhood, which opened in Bethnal Green just weeks after the station did in May 1872.",
    "Camden Road": "The current station is one of six Italianate stations designed by Edwin Henry Horne for the fast-growing North London Railway around 1870, and the last of them still in use for its original purpose.",
    "Camden Town": "Camden Town sits above the famous markets and is the most complex track junction on the network.",
    "Canada Water": "The name comes from the former Canada Dock, which handled timber shipped in from Canada; the surviving northern third now forms the freshwater lake beside the station.",
    "Canary Wharf": "Canary Wharf's cavernous Jubilee line station was designed by Norman Foster.",
    "Canning Town": "A carved staircase artwork honours the Thames Ironworks that once stood nearby, whose works football team grew into West Ham United, still nicknamed 'the Hammers'.",
    "Cannon Street": "The name has nothing to do with guns: it derives from Candlewick Street, the medieval home of the City's candle-makers, recorded as Candelwrichstrete back in 1190.",
    "Canonbury": "The area was the canons' manor of St Bartholomew's Priory, and its Tudor Canonbury Tower, the oldest building in Islington, reputedly sheltered Oliver Goldsmith from his creditors.",
    "Canons Park": "The station and surrounding park sit on the site of Canons, the grand 18th-century seat of James Brydges, first Duke of Chandos, though the name Canons itself predates him, coming from the Augustinian canons of St Bartholomew's priory who once held the land.",
    "Carpenders Park": "The original 1914 station was built to serve a nearby golf course and stood some 230 yards north of today's island platform, which opened in 1952.",
    "Chadwell Heath": "The name comes from the Old English for cold spring or cold well, recorded in 1254 as Chaudewell, though local tradition instead links it to St Chad.",
    "Chalfont & Latimer": "It is the junction for the largely single-track branch to Chesham, which at about 3.9 miles forms the longest gap between any two adjacent stations on the Underground.",
    "Chalk Farm": "Its wedge-shaped oxblood frontage is the longest of any station designed by Leslie Green, and the Roundhouse arts venue, a former railway engine shed, stands nearby.",
    "Chancery Lane": "When lifts gave way to escalators, a new ticket hall opened in 1934 below the road junction by Gray's Inn and Hatton Garden, London's diamond and jewellery quarter.",
    "Charing Cross": "Charing Cross marks the point from which all distances to London are traditionally measured.",
    "Chesham": "Chesham is the westernmost station on the Underground, on a lonely single-track Metropolitan branch.",
    "Cheshunt": "Near here ran the horse-drawn Cheshunt Railway of 1825, reputedly the world's first passenger-carrying monorail and the first railway line to open in Hertfordshire.",
    "Chigwell": "This leafy Essex village station sits on the Hainault Loop, a roughly 6.5-mile curve of the Central line that branches off the main line at Newbury Park and rejoins it at Woodford.",
    "Chingford": "A short walk away stands Queen Elizabeth's Hunting Lodge, a timber Tudor standing completed in 1543 for Henry VIII so he could view the deer chase in Epping Forest.",
    "Chiswick Park": "Rebuilt by Charles Holden in 1932, its drum-shaped ticket hall recalls his Arnos Grove design but adds a tall brick tower, and Piccadilly line trains have always run through here non-stop without ever calling.",
    "Chorleywood": "In his 1973 BBC film Metro-land, Sir John Betjeman called this Hertfordshire commuter village 'essential Metro-land', the railway-suburb dream sold by the Metropolitan Railway.",
    "Clapham Common": "Clapham Common keeps one of the Underground's last narrow Victorian island platforms.",
    "Clapham High Street": "Renamed from plain Clapham in 1989 to avoid confusion with Clapham Junction, it now sits on the Windrush line, named for the Caribbean Windrush generation.",
    "Clapham Junction": "Despite the name it is in Battersea, not Clapham, and is one of Britain's busiest interchanges, with more than 2,000 trains a day passing through.",
    "Clapham North": "It is one of only two Underground stations left with a single narrow island platform shared by both directions in the tunnel, roughly 3.7 metres wide, the other being neighbouring Clapham Common.",
    "Clapham South": "A WWII deep-level shelter beneath Clapham South later housed Windrush arrivals in 1948.",
    "Clapton": "The name derives from the Old English for farm on the hill, denoting the high ground that rises from the River Lea, recorded from 1339 as Clopton.",
    "Cockfosters": "Cockfosters, the Piccadilly line's northern terminus, is a soaring Charles Holden concrete hall.",
    "Colindale": "It is the nearest station to the RAF Museum, on the former Hendon Aerodrome, a cradle of British aviation that hosted the first official UK airmail flight in 1911.",
    "Colliers Wood": "It sits near the old Merton Abbey works on the River Wandle, where William Morris ran his textile and dye operation from 1881, having chosen the site after judging the river water suitable for dyeing.",
    "Covent Garden": "Covent Garden to Leicester Square is the network's shortest hop, about 260 m, and famously not worth the fare.",
    "Crossharbour": "Named after Glengall Bridge across the Millwall Inner Dock, it was called 'Crossharbour and London Arena' until the arena was demolished in 2006 and the older name returned.",
    "Crouch Hill": "It sits beside the Parkland Walk, laid along a disused Great Northern Railway line whose last passenger train ran in 1954 and now London's longest local nature reserve.",
    "Croxley": "Nearby Croxley Green was home to John Dickinson's paper mill, opened in 1830 and maker of the well-known Croxley Script stationery, which closed in 1980 after 150 years.",
    "Crystal Palace": "It opened in June 1854 to carry visitors to the relocated Crystal Palace at Sydenham, and its station boasted a 72-foot double-span roof on wooden arches.",
    "Custom House": "The station takes its name from the customs house of the Royal Victoria Dock, opened in 1855, and now serves ExCeL London, the vast exhibition centre on the dock's northern quay.",
    "Cutty Sark": "A minute's walk away sits its namesake, the Cutty Sark, the world's sole surviving tea clipper, dry-docked in the heart of Greenwich since 1954.",
    "Cyprus": "It takes its name from the Cyprus Estate, dockworkers' housing named to mark Britain's 1878 acquisition of the Mediterranean island.",
    "Dagenham East": "Just south lay the Ford plant, scene of the 1968 women machinists' strike for equal pay that inspired the film Made in Dagenham.",
    "Dagenham Heathway": "It serves the vast Becontree estate, built by the London County Council in the 1920s and 30s and reckoned the largest public housing estate in the world, housing around 100,000 people.",
    "Dalston Junction": "Closed in 1986, the station lay derelict for decades before reopening in 2010 as the northern terminus of the extended East London line, now the Windrush line.",
    "Dalston Kingsland": "The station sits near Ridley Road Market, a bustling street market trading since the 1880s on land then owned by a holder named after Nicholas Ridley, the Tudor Bishop of London.",
    "Debden": "Every Bank of England banknote in circulation is printed nearby at the Bank's Debden works, which has produced the country's notes since 1956.",
    "Denmark Hill": "The hill is said to be named after Prince George of Denmark, husband of Queen Anne, who reputedly hunted here; the station now serves King's College Hospital and the Maudsley.",
    "Deptford Bridge": "It marks the 'deep ford' that gave Deptford its name, where the Roman-paved route of Watling Street crossed the River Ravensbourne.",
    "Devons Road": "This Bromley-by-Bow stop was one of the DLR's original stations opened in 1987 and keeps some of that era's distinctive half-barrel platform shelters.",
    "Dollis Hill": "Mark Twain stayed at nearby Dollis Hill House in the summer of 1900, later writing that it came nearer to being a paradise than any home he had occupied; its grounds are now Gladstone Park.",
    "Ealing Broadway": "It is a rare triple terminus, the western end of both the Central and District lines and a stop on the Elizabeth line.",
    "Ealing Common": "Charles Holden gave it a tall heptagonal Portland stone ticket hall in 1931, its seven-sided form one of his early Underground experiments in geometric design.",
    "Earl's Court": "Earl's Court got the Underground's first escalators in 1911, and a full-size TARDIS police box still stands outside.",
    "East Acton": "It is the closest Underground station to HM Prison Wormwood Scrubs, the Victorian jail about ten minutes' walk away.",
    "East Finchley": "East Finchley is watched over by 'The Archer', a statue aiming his bow straight down the line towards the City.",
    "East Ham": "Its platform canopies and cast-iron columns survive from the London, Tilbury and Southend Railway station of 1858, with brackets still bearing the LTSR initials.",
    "East India": "It is named after the East India Docks where ships of the Honourable East India Company once unloaded cargo from the Indian subcontinent.",
    "East Putney": "It serves the Putney end of the Thames where the Oxford and Cambridge Boat Race begins its run to Mortlake each spring.",
    "Eastcote": "The name derives from Ascot, the eastern of the three medieval tithings of the parish of Ruislip, alongside Westcot and Norwood.",
    "Edgware": "It sits at the northern end of the old Roman Watling Street, the road now better known further south as the Edgware Road.",
    "Edgware Road": "London has two separate Edgware Road stations, almost side by side but never connected.",
    "Edmonton Green": "The essayist Charles Lamb spent his final years at a cottage in nearby Church Street, dying in Edmonton in 1834; the station was renamed in 1992 after the adjacent shopping centre.",
    "Elephant & Castle": "The district is named after a coaching inn, and one widely repeated explanation links its sign to the Cutlers' Company crest of an elephant bearing a castle, a nod to ivory knife handles; the rival 'Infanta of Castile' story is generally dismissed as a myth.",
    "Elm Park": "It was opened in 1935 specifically to serve the new Elm Park Garden City estate that Costain was building on former Hornchurch farmland.",
    "Elverson Road": "Opened in 1999 on the extension that first took the DLR under the Thames to Lewisham, it sits beside the River Ravensbourne in Brookmill Park.",
    "Embankment": "Its District line platforms sit inside Joseph Bazalgette's Victoria Embankment, built by cut-and-cover in conjunction with his great Thames sewer and opened in 1870.",
    "Emerson Park": "The sole intermediate stop on the single-track Romford to Upminster branch, it is one of the least used stations on the entire London Overground.",
    "Enfield Town": "The original station-house stood on the site of a late 17th century building reputedly the birthplace of Isaac D'Israeli and later a school where the poet John Keats was educated.",
    "Epping": "Epping is the Central line's northern terminus; trains once carried on to Ongar.",
    "Euston": "Its forecourt once held the Euston Arch, a vast Doric propylaeum of 1837, controversially demolished during the station's rebuilding in 1961 and 1962.",
    "Euston Square": "It opened in 1863 as Gower Street, one of the original stations on the Metropolitan Railway, the world's first underground railway, and took its present name in 1909.",
    "Fairlop": "It is named after the Fairlop Oak, a vast ancient tree on Hainault's Fairlop Plain that was felled by a gale in 1820.",
    "Farringdon": "An original terminus of the 1863 Metropolitan Railway, it is now the only station served by both the east-west Elizabeth line and the north-south Thameslink.",
    "Finchley Central": "It opened in 1867 on the Great Northern Railway under earlier names and was given its current 'Finchley Central' title only in 1940, around the time it was absorbed into the Northern line's Northern Heights scheme.",
    "Finchley Road": "On the old Metropolitan route just to its south once stood two now-closed stations, Marlborough Road and Lord's, both shut in 1939 when services were transferred to deep-level Bakerloo tunnels.",
    "Finchley Road & Frognal": "Opened in 1860 as Finchley Road (St John's Wood) on the Hampstead Junction Railway, it gained the Frognal suffix in 1880 and now serves the leafy fringes of Hampstead.",
    "Finsbury Park": "The park it is named for was created in the 1860s as a green space for the overcrowded Finsbury district roughly three miles to the south, which had no sizeable park of its own, on the old Hornsey Wood site.",
    "Forest Gate": "The name comes from a gate that once stood across the road to stop cattle straying from Wanstead Flats, part of Epping Forest, onto the old Roman road.",
    "Forest Hill": "A short walk away stands the Horniman Museum, famous for an overstuffed Victorian walrus whose taxidermist, unfamiliar with the animal, smoothed out its natural skin folds.",
    "Fulham Broadway": "Known as Walham Green until 1952, it is the nearest station to Chelsea's Stamford Bridge stadium.",
    "Gallions Reach": "This stretch of the Thames is named after the Galyons, a family recorded as owning riverside property here from around 1330, and not after galleons despite the spelling.",
    "Gants Hill": "Gants Hill's grand barrel-vaulted concourse was modelled on the Moscow Metro.",
    "Gidea Park": "The station opened in 1910 to serve the Romford Garden Suburb, an Arts and Crafts town-planning showcase whose 1911 exhibition featured around 140 furnished houses.",
    "Gloucester Road": "Opened in 1868, it is named after Gloucester Road itself, which took its name from Maria, Duchess of Gloucester, who built a house in the area, and it now serves the South Kensington museum quarter.",
    "Golders Green": "When the tube reached it in 1907 it served open countryside with only a handful of houses, but the station triggered a building boom that turned the hamlet into a populous suburb within a few years.",
    "Goldhawk Road": "The road and station take their name from one John Goldhawk, who held estates in the Fulham area in the late 14th century.",
    "Goodge Street": "A WWII deep-level shelter under Goodge Street served as a military headquarters.",
    "Goodmayes": "The name derives from the family of John Godemay, referred to in a document of 1319, long before the station opened in 1901 on the Great Eastern Main Line.",
    "Gospel Oak": "Named for an oak on the Hampstead and St Pancras parish boundary where gospel passages were reputedly read during the beating of the bounds; it sits beside Hampstead Heath.",
    "Grange Hill": "Despite sharing its name with the famous school drama, the station has no link to the show, which was filmed elsewhere; 'grange' simply meant a farm with a granary, here on a hill.",
    "Great Portland Street": "Opened in 1863 as Portland Road, it was a stop on the Metropolitan Railway, the world's first underground line, and today stands near Regent's Park and Madame Tussauds.",
    "Green Park": "The royal park it serves is famously free of formal flowerbeds, traditionally said to be because a queen ordered the blooms torn up after a king picked them for another woman.",
    "Greenford": "Greenford had the Underground's last wooden escalator, since replaced by its only inclined lift.",
    "Greenwich": "The station shares its site with the National Rail Greenwich station and is a short walk from the maritime town centre, the Cutty Sark and Greenwich Park, home of the Royal Observatory and the Prime Meridian.",
    "Gunnersbury": "Its name reputedly traces to Gunnhild, said to be a niece of King Canute, though scholars read it more soberly as a Norse personal name plus the Old English 'bury' for fortified manor.",
    "Hackney Central": "Steps from the station stands the Hackney Empire, a 1901 Frank Matcham music hall where Charlie Chaplin, Stan Laurel and Marie Lloyd once performed.",
    "Hackney Downs": "The station is named after Hackney Downs, a roughly 40-acre open space that was historically common grazing land and was saved as parkland from the 1860s after pressure from the Commons Preservation Society.",
    "Hackney Wick": "Hackney Wick sits beside Queen Elizabeth Olympic Park and Here East, the media campus converted from the 2012 Games press and broadcast centre.",
    "Haggerston": "Haggerston, on the brick Kingsland Viaduct, reopened in 2010, reviving a stop whose original station had been closed during the Second World War and later demolished.",
    "Hainault": "The name is Old English for a wood belonging to a religious community, recalling Barking Abbey's hold on the former Hainault Forest, and the station sits beside the Central line's main eastern depot.",
    "Hammersmith": "Hammersmith is in fact two separate, unlinked stations either side of the Broadway, near the art deco Eventim Apollo where the Beatles played a Christmas variety run over 1964 and 1965.",
    "Hampstead": "At 58.5 m below the surface, Hampstead is the deepest station on the Underground.",
    "Hampstead Heath": "The station serves Hampstead Heath, the large London common whose Parliament Hill offers one of the city's protected skyline views.",
    "Hanger Lane": "The station building sits marooned in the middle of the Hanger Lane gyratory, a notorious roundabout reached only by pedestrian subways beneath the traffic.",
    "Hanwell": "Just east of Hanwell stands Brunel's Wharncliffe Viaduct of 1837, the first major structure completed on the Great Western Railway and now Grade I listed.",
    "Harlesden": "Harlesden station opened on 15 June 1912 on the London and North Western Railway's new electrified suburban tracks, the route Bakerloo trains began serving on 1 August 1917 after the line's extension towards Watford.",
    "Harold Wood": "Harold Wood is reputedly named for King Harold Godwinson, who is said to have held land in the surrounding area before his defeat at Hastings in 1066.",
    "Harringay Green Lanes": "It serves Green Lanes, thought to have begun as a drovers' road for herding livestock towards London's markets, now the spine of the Victorian terraced grid known as the Harringay Ladder.",
    "Harrow & Wealdstone": "It was the scene of Britain's worst peacetime rail crash in October 1952, a three-train pile-up in morning fog that killed 112 people and hastened the spread of automatic train warning systems.",
    "Harrow-on-the-Hill": "The hill rises to about 124 metres and is crowned by Harrow School, founded in 1572 by local landowner John Lyon under a royal charter from Elizabeth I.",
    "Hatch End": "Betjeman described its Grade II listed 1911 station building, in Wren Revival style by Gerald Horsley, as half-way between a bank and a medium-sized country house.",
    "Hatton Cross": "The station opened in 1975 and served as the temporary terminus for the Heathrow extension until the airport's own station opened in 1977, making it one of the shortest-lived termini on the network.",
    "Hayes & Harlington": "A short walk away is the Old Vinyl Factory, EMI's Hayes plant that pressed records for the Beatles, the source of the 'Hayes, Middlesex' wording on their early sleeves.",
    "Headstone Lane": "The station takes its name from nearby Headstone Manor, a moated medieval manor house whose timber-framed hall dates to the early fourteenth century.",
    "Heathrow Terminal 4": "This station serves Heathrow's Terminal 4, which sits on the airport's southern side away from the central cluster of terminals.",
    "Heathrow Terminal 5": "The station opened in 2008 alongside Terminal 5, a vast Richard Rogers Partnership building that served as the dedicated home of British Airways.",
    "Heathrow Terminals 2 & 3": "Originally called Heathrow Central, the station opened in 1977 and marked the first time an airport anywhere was directly served by an underground railway.",
    "Hendon Central": "The Hendon area is home to the Royal Air Force Museum London, sited on the former Hendon Aerodrome, a cradle of early British aviation that staged the first UK airmail flight.",
    "Heron Quays": "It is reputedly named after herons that 1980s surveyors spotted perched on the disused dock cranes before Canary Wharf was built.",
    "High Barnet": "At around 98 metres above sea level it is the highest open-air station on the deep-level tube network, yet it sits below the old town of Barnet, which was built up higher on the hill.",
    "High Street Kensington": "The station is entered through the glass-roofed Edwardian Kensington Arcade, built for the Metropolitan Railway around 1906 to designs by their architect George Sherrin.",
    "Highams Park": "The park's lake was created by the landscape designer Humphry Repton in 1794 by damming the River Ching, as part of his work on the Highams estate.",
    "Highbury & Islington": "It is a popular match-day alternative for Arsenal supporters, lying roughly a ten-minute walk down Holloway Road from the Emirates Stadium.",
    "Highgate": "Highgate's abandoned surface platforms are now a wooded nature reserve and bat roost.",
    "Hillingdon": "The station was demolished and rebuilt to the south in 1992 to let the A40 be widened, and the Cassidy Taggart design went on to win the 1994 Underground Station of the Year award.",
    "Holborn": "It still hides a disused platform from the Aldwych shuttle branch, closed in 1994, since used to trial London Underground signage and seen on guided 'Hidden London' tours.",
    "Holland Park": "The station serves Holland Park, laid out around the bomb-damaged ruins of the Jacobean Holland House and home to the Kyoto Garden, a 1991 gift from the city of Kyoto.",
    "Holloway Road": "Holloway Road housed an experimental spiral escalator designed by Jesse Reno and built in 1906, dismantled by 1911 with no firm evidence it ever carried passengers, its remains rediscovered in the lift shaft in 1988.",
    "Homerton": "Homerton lends its name to Homerton University Hospital and to Homerton College, Cambridge, which grew from a dissenting academy once based on Homerton High Street before moving to Cambridge in 1894.",
    "Honor Oak Park": "The name comes from the Oak of Honor on nearby One Tree Hill, a tree under which Elizabeth I is reputed to have picnicked in 1602 and which marked an old boundary.",
    "Hornchurch": "The name is thought to derive from a medieval monastery here recorded in Latin as the horned monastery, and the parish church of St Andrew still bears a stone bull's head with copper horns on its east gable.",
    "Hounslow Central": "Hounslow Central opened on 1 April 1886 as Heston-Hounslow and kept that name until 1 December 1925, when the three Hounslow stations were given their compass-point titles of east, central and west.",
    "Hounslow East": "Hounslow East began life on 2 May 1909 as Hounslow Town, and was renamed to its compass-point title on 1 December 1925.",
    "Hounslow West": "Hounslow West opened on 21 July 1884 as Hounslow Barracks, named after the nearby Cavalry Barracks, and gained Charles Holden's Grade II listed heptagonal ticket hall in 1931.",
    "Hoxton": "The station sits beside the Museum of the Home, the former Geffrye Museum housed in early eighteenth-century almshouses, whose entrance was reoriented towards the railway during its refurbishment.",
    "Hyde Park Corner": "It is one of the few deep-level Tube stations with no building above ground, reached only through pedestrian subways, while Decimus Burton's Wellington Arch stands nearby above the junction.",
    "Ickenham": "Ickenham appears in the Domesday Book as Ticheham, its name meaning the homestead of a Saxon called Tic(c)a, with the initial T later lost through confusion with the Middle English word for 'at'.",
    "Ilford": "On New Year's Day 1915 an express from Clacton ran into a local train at Ilford station, killing ten people in one of the line's worst collisions.",
    "Imperial Wharf": "One of the newer stations in the country, it opened in 2009 by the Thames, with Chelsea Harbour Pier and its Thames Clippers boats about 250 metres away.",
    "Island Gardens": "From the gardens beside the station you get the Canaletto view of Greenwich across the Thames, reached on foot via the Greenwich foot tunnel, which opened in 1902.",
    "Iver": "Iver is the nearest station to Pinewood Studios at Iver Heath, whose name was chosen for the pine trees on the estate and to echo the American film centre Hollywood.",
    "Kennington": "Kennington has a circular tunnel 'loop' where Northern line trains turn around underground.",
    "Kensal Green": "Kensal Green serves the oldest of London's Magnificent Seven cemeteries, consecrated in 1833 and resting place of Isambard Kingdom Brunel and Charles Babbage.",
    "Kensal Rise": "The library near Kensal Rise station was opened by Mark Twain in 1900 and is said to be the only library he ever opened.",
    "Kensington": "Kensington (Olympia) adjoins the Olympia exhibition centre, which opened in 1886 as the National Agricultural Hall and is still served by District line trains only at weekends and during events.",
    "Kentish Town": "Kentish Town, unrelated to the county of Kent, probably takes its name from Ken-ditch meaning the bed of a waterway, here the now-hidden River Fleet.",
    "Kentish Town West": "Closed after a serious fire in 1971 and once slated for permanent closure, Kentish Town West was rebuilt and reopened in 1981, funded by the Greater London Council.",
    "Kenton": "Kenton means the farm of a Saxon called Coena, and was recorded as Keninton as far back as 1232.",
    "Kew Gardens": "The station is the closest stop to the Royal Botanic Gardens, a UNESCO World Heritage Site whose Treetop Walkway carries visitors 18 metres up through the canopy.",
    "Kilburn": "Kilburn takes its name from a stream first recorded in 1134 as Cuneburna, beside which the hermit Godwyn's cell grew into Kilburn Priory on the old Watling Street.",
    "Kilburn High Road": "Opened in 1852 as Kilburn and Maida Vale, this station once had platforms on all four tracks of the West Coast Main Line out of Euston.",
    "Kilburn Park": "Kilburn Park, opened in 1915 to a Stanley Heaps design, was among the first Tube stations built for escalators rather than lifts, so it needed no engine room and was raised as a single-storey building.",
    "King George V": "It is named after the last of London's upstream royal docks, opened by George V in 1921 and large enough to berth liners such as the Mauretania.",
    "King's Cross St. Pancras": "King's Cross St Pancras is the Underground's busiest interchange (six lines), and Platform 9¾ is next door.",
    "Kingsbury": "Kingsbury, meaning the king's fortification, lies near the Welsh Harp reservoir, an SSSI that hosted the women-only 1960 European Rowing Championships.",
    "Knightsbridge": "Knightsbridge is named from a bridge over the now-buried River Westbourne, the cniht of its name meaning young men or retainers rather than mounted warriors.",
    "Ladbroke Grove": "Opened in 1864 simply as Notting Hill, the station sits on the route of the Notting Hill Carnival and is a short walk from Portobello Road Market.",
    "Lambeth North": "The nearest stop to the Imperial War Museum, it opened in 1906 as Kennington Road and was renamed three times before settling on its current name in 1928.",
    "Lancaster Gate": "It is named after a nearby entrance to Kensington Gardens, itself named in honour of Queen Victoria in her role as Duke of Lancaster.",
    "Langdon Park": "Opened in December 2007 to fill one of the longest gaps on the DLR, it takes its name from the adjacent park rather than its provisional name, Carmen Street.",
    "Langley": "The name Langley comes from Old English for a long wood or clearing, and the station retains a Brunel-era building on the Great Western main line.",
    "Latimer Road": "Grenfell Tower stands behind the station and is clearly visible from the Paddington-bound platform; the name comes from a road honouring Edward Latymer, a 17th-century benefactor who endowed the Latymer schools.",
    "Leicester Square": "Leicester Square is the West End's cinema heart and the home of film premieres.",
    "Lewisham": "The name means the homestead of a Saxon called Leofsa, an early settlement near the meeting of the Ravensbourne and Quaggy rivers.",
    "Leyton": "The name means settlement on the River Lea, the river that forms the western boundary of this area in the Lower Lea Valley.",
    "Leyton Midland Road": "On 17 August 1915 bombs from the German Zeppelin L.10 struck Leyton Midland Road, destroying the ticket office and a billiard hall in the arches below.",
    "Leytonstone": "Alfred Hitchcock was born nearby in 1899, and the station passages are lined with mosaics made from more than 80,000 tiles depicting scenes from his films.",
    "Leytonstone High Road": "Alfred Hitchcock was born on 13 August 1899 above his family's greengrocer's shop at 517 Leytonstone High Road, near the station.",
    "Limehouse": "The name comes from the medieval lime oasts, kilns that burned chalk into lime by the river, and not from the limeys who later landed there.",
    "Liverpool Street": "Crossrail digging at Liverpool Street uncovered the Bedlam burial ground and thousands of skeletons.",
    "London Bridge": "London Bridge is overlooked by the Shard, western Europe's tallest building.",
    "London City Airport": "The airport runway runs between the Royal Albert and King George V docks, and the station has a covered connection straight into the terminal building.",
    "London Fields": "London Fields is named after the adjacent Hackney common, recorded as 'London Field' by 1540, where drovers pastured livestock before driving them to market.",
    "Loughton": "Its 1940 station building, with sweeping cantilevered concrete platform canopies, is Grade II listed and serves a town on the edge of Epping Forest.",
    "Maida Vale": "Maida Vale opened in 1915 staffed entirely by women, while the men were away at war.",
    "Maidenhead": "Just east of Maidenhead stands Brunel's railway bridge, with reputedly the flattest brick arches ever built, immortalised in Turner's 'Rain, Steam and Speed'.",
    "Manor House": "Designed by Charles Holden and opened in 1932, it is reputedly the only Piccadilly line station named after a former public house.",
    "Manor Park": "Manor Park sits beside the City of London Cemetery, one of Europe's largest municipal burial grounds, laid out in the 1850s with the nearby railway among the reasons for the site.",
    "Mansion House": "It is named after the Lord Mayor of London's grand Palladian official residence, though oddly Bank station actually sits closer to that building.",
    "Marble Arch": "The station sits near the historic site of the Tyburn gallows, London's main public execution ground for centuries until 1783.",
    "Maryland": "Maryland is reputedly named after the American colony by a merchant who settled here after returning from across the Atlantic, though historians dispute the story.",
    "Marylebone": "Opened in 1899, it was the last main line terminus built in London and has featured as a filming location in the Beatles' film A Hard Day's Night.",
    "Mile End": "It is the only underground station on the network offering cross-platform interchange between a deep-tube line (Central) and sub-surface lines (District and Hammersmith & City).",
    "Mill Hill East": "The terminus of a single-track Northern line spur, it was kept in service during the war largely to serve the nearby Inglis Barracks.",
    "Monument": "Monument is named after Wren's column commemorating the Great Fire of London, just outside.",
    "Moor Park": "It opened in 1910 as Sandy Lodge, named after the adjacent golf course, before taking its present name from the surrounding private estate.",
    "Moorgate": "Named after a gate in the old city wall demolished in the 1760s, it was the scene of the 1975 tube crash that killed 43, the deadliest peacetime accident in Underground history.",
    "Morden": "Morden is the southernmost station on the network, in a striking 1926 Charles Holden building.",
    "Mornington Crescent": "Mornington Crescent lends its name to the surreal game on BBC radio's I'm Sorry I Haven't a Clue.",
    "Mudchute": "The name comes from spoil dredged out of Millwall Dock and dumped here through a chute, later turned into a park and city farm.",
    "Neasden": "It sits beside Neasden Depot, the Metropolitan Railway's carriage and locomotive works from the 1880s and still the largest depot on the Underground.",
    "New Cross": "New Cross is thought to take its name from a turnpike toll gate set up on the Kent road in 1718, beside a hostelry called the New Cross House, itself a successor to an older coaching inn known as the Golden Cross.",
    "New Cross Gate": "Millwall's ground, The Den, stands at New Cross Gate, and the Overground line through the station is named the Windrush line to honour the Caribbean Windrush generation.",
    "Newbury Park": "Its bus station, a copper-clad barrel-vaulted shelter by Oliver Hill, won a Festival of Britain award in 1951 and is now Grade II listed.",
    "Nine Elms": "Opened in 2021 on the Northern line extension, it serves the US Embassy and takes its name from a row of elm trees recorded along the lane around 1645.",
    "North Acton": "For decades the BBC ran its main television rehearsal rooms and costume store beside the line here, and the area borders the vast Park Royal industrial estate.",
    "North Ealing": "It is the only station to survive from the District Railway's westward expansion of 1899 to 1903, retaining its richly detailed country-style station house.",
    "North Greenwich": "North Greenwich serves the O2 Arena, the former Millennium Dome.",
    "North Harrow": "It opened in 1915, the same year the Metropolitan Railway coined the Metro-land brand for the housing estates it was promoting across these fields.",
    "North Wembley": "It is served by the Lioness line, the Overground route named in 2024 to honour the England women's team who won Euro 2022 at nearby Wembley.",
    "Northfields": "Charles Holden rebuilt it in 1932 in brick, concrete and glass to serve the new Piccadilly line depot next door, and it is now Grade II listed.",
    "Northolt": "It shares its name with nearby RAF Northolt, which opened in 1915 as Britain's oldest RAF airfield and was home to the Polish No. 303 Squadron during the Battle of Britain.",
    "Northwick Park": "It is a short walk from Northwick Park Hospital, a major north-west London teaching hospital run by London North West University Healthcare NHS Trust.",
    "Northwood": "Opened by the Metropolitan Railway in 1887, it gives its name to the nearby Northwood military headquarters that hosts NATO's Allied Maritime Command and the UK's Permanent Joint Headquarters.",
    "Northwood Hills": "Opened in 1933, its name was chosen by public competition, with the winning entry reputedly suggested by a woman from North Harrow.",
    "Norwood Junction": "Norwood Junction opened in 1839 as Jolly Sailor station, named after a nearby pub, before being renamed Norwood in 1845 and Norwood Junction by the 1850s.",
    "Notting Hill Gate": "The name recalls a tollgate that once stood on the road here, and the area now hosts Europe's largest street festival, the Notting Hill Carnival.",
    "Oakwood": "Charles Holden's box-like ticket hall here is Grade II* listed; the station opened in 1933 as Enfield West and was renamed Oakwood only in 1946 after pressure from Southgate Council.",
    "Old Street": "Old Street's roundabout was the heart of London's 'Silicon Roundabout' tech scene.",
    "Osterley": "The station sits near the National Trust's Osterley Park, an Elizabethan mansion later remodelled by Robert Adam, and the name is thought to derive from Old English for the sheepfold in the clearing.",
    "Oval": "Oval is named after the adjacent cricket ground, the world's first international cricket venue.",
    "Oxford Circus": "In 2009 it gained one of Britain's first large diagonal scramble crossings, inspired by Tokyo's Shibuya, set atop a junction John Nash created as part of his Regent Street scheme of the 1810s.",
    "Paddington": "Brunel's 1854 terminus, with its glass and wrought-iron barrel roofs influenced by the Crystal Palace, later lent its name to Michael Bond's marmalade-loving bear.",
    "Park Royal": "The name comes from a short-lived Royal Agricultural Society showground opened nearby in 1903; the area later became a vast industrial estate and the site of a Guinness brewery.",
    "Parsons Green": "Named after the Fulham green where the parson reputedly kept his bowling green, the station opened in 1880 with the District Railway's extension to Putney Bridge.",
    "Peckham Rye": "Above the booking hall hides a vast Victorian waiting room designed by Charles Henry Driver in 1865, bricked up in 1962 and later rediscovered and restored for public use.",
    "Penge West": "First opened in 1839 by the London and Croydon Railway, it served a village of only about 270 people, closed in 1841, then reopened in 1863 to ferry visitors to the nearby Crystal Palace.",
    "Perivale": "Beside the station stands the Hoover Building, a 1933 Art Deco factory that John Betjeman likened to a sort of Art Deco Wentworth Woodhouse.",
    "Piccadilly Circus": "Piccadilly Circus has no surface building at all, its ticket hall is entirely underground, beneath Eros.",
    "Pimlico": "Pimlico is the only Victoria line station with no interchange, and the closest stop to Tate Britain.",
    "Pinner": "This Metro-land village holds Pinner Fair, traced to a 1336 charter granted under Edward III, making it one of the country's longest-surviving street fairs.",
    "Plaistow": "The name is widely thought to come from Old English for a place of sport or play, reputedly where miracle plays were once performed, and it lies in West Ham in the borough of Newham.",
    "Pontoon Dock": "Raised high on a viaduct, one of the highest elevated stations on the network, it offers wide views south across Thames Barrier Park towards the Thames Barrier.",
    "Poplar": "The district, and so the station, is named after the black poplar trees that once thrived in the wet ground between the Thames and the Lea.",
    "Preston Road": "It opened in 1908 as a request halt after a nearby shooting club, which hosted 1908 Olympic events, lobbied the railway for a stop closer than the two-mile walk to Neasden.",
    "Prince Regent": "It serves the eastern end of the ExCeL exhibition centre on the north quay of the Royal Victoria Dock, and is named after nearby Prince Regent Lane.",
    "Pudding Mill Lane": "It is named after the old Pudding Mill River and a water mill said to have been shaped like a pudding, and now sits beside the Olympic Park.",
    "Putney Bridge": "Despite the name the station sits on the Fulham bank near Bishops Park, close to where the Oxford and Cambridge Boat Race course has started since 1845.",
    "Queen's Park": "The neighbouring park took the name in 1887 to mark Queen Victoria's Golden Jubilee, having earlier been laid out as a public open space on land used for an agricultural show.",
    "Queens Road Peckham": "Opened on the South London Line in 1866, the station now stands on a brick viaduct, its present island platform dating from the 1970s and reached by a long flight of steps.",
    "Queensbury": "Its name was chosen through a 1930s newspaper competition and has no historical basis, coined as a counterpoint to neighbouring Kingsbury.",
    "Queensway": "It opened in 1900 as Queen's Road near Kensington Gardens; nearby Bayswater was home to Whiteleys, often called London's first department store.",
    "Ravenscourt Park": "The name dates to 1747, when Thomas Corbett bought the medieval Paddenswick estate and renamed it Ravenscourt, reputedly after the raven in his coat of arms.",
    "Rayners Lane": "Opened as a halt in 1906, the station and its lane are named after Daniel Rayner, a local farmer who once worked the surrounding fields.",
    "Reading": "Reading opened in 1840 as the temporary western terminus of Brunel's Great Western Railway, built in his unusual single-sided layout with both platforms on the same side of the through tracks.",
    "Rectory Road": "Opened by the Great Eastern Railway in 1872, the station sits in West Hackney, between Hackney Downs and Stoke Newington in east London.",
    "Redbridge": "The name comes from a red-brick bridge over the River Roding, unusual among the area's pale-stone bridges, which was demolished around 1921 for road improvements.",
    "Regent's Park": "It is one of the few Tube stations with no surface building at all, reached by lift and a subway from Marylebone Road near the park John Nash laid out in the early 1800s.",
    "Richmond": "The town was renamed from Sheen around 1500 by Henry VII after his earldom of Richmond, and his riverside Richmond Palace later became a favourite home of Elizabeth I.",
    "Rickmansworth": "The nearby Chess Valley was watercress country, and electric tube cars on the local Watford and Rickmansworth line were nicknamed watercress trains for the crop carried in their luggage vans.",
    "Roding Valley": "Roding Valley is the least-used station on the entire Underground.",
    "Romford": "Romford's market, beside the station, has run since a royal writ of 1247 under Henry III, and by common law no rival market may open within a day's sheep drive, taken to be about 6.66 miles.",
    "Rotherhithe": "The station sits beside Brunel's Thames Tunnel, opened in 1843 as the first tunnel known to be built successfully under a navigable river, whose engine house is now the Brunel Museum.",
    "Royal Albert": "The station serves the Royal Albert Dock, which opened in 1880, was named by royal assent after Queen Victoria's late consort Prince Albert, and with its neighbours formed the largest enclosed dock system in the world.",
    "Royal Oak": "It is named after a vanished tavern, itself recalling the oak at Boscobel in which the future Charles II reputedly hid from Roundheads after the Battle of Worcester in 1651.",
    "Royal Victoria": "It sits beside the Royal Victoria Dock, which opened in 1855 as the first London dock built specifically to take large steamships and the first connected to the national railway network.",
    "Ruislip": "Close to the station, Manor Farm preserves a Norman motte-and-bailey earthwork and a great barn reputedly dating from around 1300, on ground with groundwork traced to the 9th century.",
    "Ruislip Gardens": "The station lies close to RAF Northolt, the fighter base that flew Spitfires and Hurricanes, including Polish squadrons, during the Battle of Britain.",
    "Ruislip Manor": "The Manor of Ruislip was held after the Norman Conquest by Ernulf de Hesdin, whose holding is recorded in the Domesday Book of 1086.",
    "Russell Square": "It has no escalators, so the platforms are reached by lift or by a spiral staircase of roughly 175 steps deep beneath Bloomsbury.",
    "Seven Kings": "Despite the regal name, it reputedly derives from a Saxon called Seofoca and his followers, not from any gathering of kings.",
    "Seven Sisters": "The name comes from a ring of seven elm trees planted around a central walnut on Page Green in Tottenham, a clump recorded as the Seven Sisters by 1732.",
    "Shadwell": "Shadwell's name is popularly tied to a spring by a church dedicated to St Chad, though the older root is more likely the Anglo-Saxon for a shallow well or creek.",
    "Shenfield": "Out in Essex beyond Greater London, Shenfield is an eastern terminus of the Elizabeth line, where its trains terminate on the Great Eastern Main Line.",
    "Shepherd's Bush": "The name reputedly comes from common land where shepherds rested their flocks on the drive to Smithfield Market, with Westfield and the former BBC Television Centre nearby.",
    "Shepherd's Bush Market": "The station overlooks Shepherd's Bush Market, a row of stalls lining the railway viaduct that has traded since around 1914.",
    "Shoreditch High Street": "Built on the old Bishopsgate goods yard, the station is sealed inside a concrete box on a viaduct beside the surviving Braithwaite Viaduct, one of the oldest railway structures in the world.",
    "Silver Street": "The station takes its name from the old street recorded by about 1630, reputedly alluding to silversmiths once living in this part of Edmonton.",
    "Sloane Square": "A large iron pipe slung above the platforms carries the buried River Westbourne over the tracks, a Victorian solution still in place since the station opened in 1868.",
    "Slough": "Slough's trading estate was the first European home of Mars in 1932, where Forrest Mars Sr. made the first Mars bars, a site that now turns out close to three million bars a day.",
    "Snaresbrook": "The station borders a detached portion of Epping Forest by Eagle Pond, formerly Snares Pond, whose name is sometimes linked to snares once set to trap animals or birds in the forest, though the origin is uncertain.",
    "South Acton": "South Acton is one of seven separate stations carrying the Acton name, said to give Acton more stations than any other place name in England.",
    "South Ealing": "Its name is one of only two on the Underground, with Mansion House, to contain all five vowels, and the only one to use each exactly once.",
    "South Hampstead": "The station opened in 1879 as Loudoun Road, after the street it stands on in Camden, and took its present name in 1922.",
    "South Harrow": "The 1903 Ealing to South Harrow line was, with the tracks back to Acton Town, the first stretch of the Underground's surface railways to run electric trains instead of steam.",
    "South Kensington": "An 1885 tiled pedestrian subway, still in use today, runs from the station beneath Exhibition Road, giving sheltered access towards the Natural History, Science and V&A museums.",
    "South Kenton": "South Kenton opened in 1933 as a late addition to the London and North Western Railway's 'New Line' from Euston to Watford, which had opened in 1912, once the local population had grown enough to justify a stop.",
    "South Quay": "The station stands on the southern shore of the South Dock of the old West India Docks, with its platforms set astride the channel that links Millwall Dock to the West India Docks.",
    "South Ruislip": "The rounded booking hall holds a frieze of concrete, glass and granite chips that is one of the earliest public works by the glass artist Henry Haig.",
    "South Tottenham": "A short walk away in Markfield Park stands the Markfield Beam Engine, an 1886 steam engine that once pumped Tottenham's sewage and is still steamed for the public today.",
    "South Wimbledon": "Charles Holden's station actually stands in Merton, but was named South Wimbledon because Wimbledon was reckoned the more genteel address.",
    "South Woodford": "The station sits beside Charlie Brown's Roundabout, named after the landlord of a pub called The Roundabout that was demolished in 1972 to make way for M11 slip roads.",
    "Southall": "Southall carries what is reputedly London's only bilingual roundel, giving the name in English and in Gurmukhi script for the area's large Punjabi community.",
    "Southbury": "Southbury opened in 1891 as Churchbury on the Great Eastern's loop line, and took its present name when the route reopened to passengers after electrification in 1960.",
    "Southfields": "Southfields is the most convenient Tube stop for the All England Club, so each summer it becomes the main gateway for crowds heading to the Wimbledon Championships.",
    "Southgate": "Southgate's flying-saucer station building, by Charles Holden, is so admired it is Grade II* listed.",
    "Southwark": "Its concourse holds a 40 metre curved wall of 660 pieces of blue glass by Alexander Beleschenko, inspired by Schinkel's set design for The Magic Flute.",
    "St James Street": "The station sits beside Walthamstow High Street, whose long daily market is often claimed to be the longest outdoor street market in Europe.",
    "St. James's Park": "The station is built into 55 Broadway, Charles Holden's 1929 Underground headquarters that was then the tallest office block in London and carries sculptures by Epstein, Gill and others.",
    "St. John's Wood": "It is the nearest Tube station to both Lord's Cricket Ground and the Abbey Road zebra crossing the Beatles made famous.",
    "St. Paul's": "St Paul's, beside Wren's cathedral, was renamed from 'Post Office' in 1937.",
    "Stamford Brook": "On 5 January 1964 Stamford Brook became the first station on the entire London Underground to be fitted with an experimental automatic ticket barrier.",
    "Stamford Hill": "Stamford Hill is home to the largest Hasidic Jewish community in Europe, numbering around 30,000 people with dozens of synagogues clustered nearby.",
    "Stanmore": "Stanmore opened in 1932 as the Metropolitan Railway's terminus of a branch from Wembley Park, later passing to the Bakerloo line in 1939 and then to the Jubilee line in 1979.",
    "Star Lane": "This stop near Canning Town was shown on some early maps as Cody Road before opening in 2011, but was instead named after the nearby Star Lane.",
    "Stepney Green": "The station sits beside Stepney Green, a surviving slice of the old Mile End Green common where Essex rebels gathered before Richard II met them during the Peasants' Revolt of 1381.",
    "Stockwell": "A WWII deep-level shelter sits beneath Stockwell, its surface rotunda now a war memorial.",
    "Stoke Newington": "Nearby Abney Park is one of London's Magnificent Seven Victorian cemeteries, in the area where Daniel Defoe lived on Church Street while writing Robinson Crusoe.",
    "Stonebridge Park": "Just north-west of the station lies Stonebridge Park Depot, the main stabling and maintenance depot for the Bakerloo line.",
    "Stratford": "Stratford was the gateway to the 2012 Olympic Park.",
    "Stratford High Street": "The station occupies the site of the old Stratford Bridge station on the nineteenth-century line between Stratford and Canning Town, and the original red-brick station buildings still stand on the south side of the High Street.",
    "Stratford International": "Despite the name no international trains have ever stopped here: planned Eurostar calls never ran, and it is served only by domestic High Speed 1 Southeastern trains and the DLR.",
    "Sudbury Hill": "Sudbury Hill is a smaller red-brick version of Charles Holden's 'brick box with a concrete lid' that he pioneered at neighbouring Sudbury Town.",
    "Sudbury Town": "Sudbury Town set the template for Charles Holden's 1930s 'brick box with a concrete lid' stations.",
    "Surrey Quays": "Opened in 1869 as Deptford Road, the station was renamed Surrey Quays in 1989 after the shopping centre built on the old Surrey Commercial Docks.",
    "Swiss Cottage": "The station is named after a chalet-style pub built around 1804 as the Swiss Tavern at the road junction above, later called Ye Olde Swiss Cottage, which closed in early 2025.",
    "Sydenham": "The line through Sydenham opened in 1839 along the drained bed of the failed Croydon Canal, which an Act of Parliament had abandoned only three years earlier.",
    "Taplow": "The station is the nearest stop to Cliveden, the grand Thames-side estate later infamous as the setting of the 1960s Profumo affair.",
    "Temple": "Temple takes its name from the medieval Temple and the Inns of Court above it.",
    "Theobalds Grove": "The station is named after nearby Theobalds Palace, a favourite residence of King James I, who died there in 1625.",
    "Theydon Bois": "The 'Bois' comes from the medieval de Bois family who held the manor, and a parish clerk reputedly recommended the French spelling for the village's forest setting.",
    "Tooting Bec": "The Bec recalls Bec Abbey in Normandy, which held the manor, and nearby Tooting Bec Lido is the largest freshwater pool by surface area in the UK.",
    "Tooting Broadway": "A bronze statue of King Edward VII, erected by public subscription and unveiled in 1911, stands just outside the station.",
    "Tottenham Court Road": "Tottenham Court Road is lined with Eduardo Paolozzi's vivid 1980s mosaics.",
    "Tottenham Hale": "'Hale' is traditionally said to derive from an Old English word for hoisting, marking where goods such as timber were unloaded from boats on the River Lea.",
    "Totteridge & Whetstone": "Whetstone is reputedly where soldiers sharpened their blades before the 1471 Battle of Barnet, though the name predates the battle, so the tale is folklore.",
    "Tower Gateway": "Opened in 1987 as the original western terminus of the DLR, it stands near the Tower of London, from which it takes its name.",
    "Tower Hill": "Tower Hill is the stop for the Tower of London and Tower Bridge.",
    "Tufnell Park": "The district and station are named after William Tufnell, who was granted the manor of Barnsbury in 1753.",
    "Turkey Street": "The name has nothing to do with the bird: it is reputedly a folk-etymology corruption of an earlier 'Tuckey Street', after a landholder called Tuckey.",
    "Turnham Green": "The 1642 Battle of Turnham Green, a Civil War standoff that turned Charles I back from London, was fought across open fields near here now built over by Chiswick.",
    "Turnpike Lane": "It is named after a toll gate erected on Green Lanes in 1765 by the Stamford Hill and Green Lanes Turnpike Trust.",
    "Twyford": "Twyford is the junction for the branch line to Henley-on-Thames, and was briefly the western terminus of Brunel's Great Western Railway from 1839 to 1840.",
    "Upminster": "A short walk away stands Upminster Windmill, a Grade II* listed smock mill built in 1803 and widely regarded as one of the finest surviving English smock mills.",
    "Upminster Bridge": "A large reversed swastika, an innocent good-luck motif when laid in 1934, is tiled into the floor of the station's ticket hall.",
    "Upney": "The station takes its name from Upney Lane in Barking, and the old place name is usually read as a 'higher' patch of dry ground or island in the marshes, from the Old English element 'eg'.",
    "Upper Holloway": "The station sits on Holloway Road just north of Whittington Park and close to the Whittington Hospital, both named after Dick Whittington, the medieval Lord Mayor of London later turned into a pantomime figure.",
    "Upton Park": "It is the local stop for West Ham United's old Boleyn Ground, which took its name from the adjacent Green Street House, reputedly linked by local legend to Anne Boleyn, and which the club called home until 2016.",
    "Uxbridge": "Charles Holden's 1938 station is Grade II listed and lit by stained glass by the Hungarian artist Ervin Bossanyi showing the heraldry of Middlesex and Buckinghamshire.",
    "Vauxhall": "Vauxhall is often credited as the origin of the Russian word for a railway station, 'vokzal'.",
    "Victoria": "One of the Underground's busiest stations, it sits east of Buckingham Palace Road and just south of Victoria Street, from which it takes its name.",
    "Walthamstow Central": "Walthamstow Central, the Victoria line's northern terminus, is near the William Morris Gallery.",
    "Walthamstow Queens Road": "Despite the name, the station actually stands at the northern end of Edinburgh Road, facing the Queen's Road cemetery rather than the road itself.",
    "Wandsworth Road": "The station had five platforms after a high-level route was added in 1866, but the three extra platforms closed in 1916 and were later demolished.",
    "Wanstead": "Wanstead's unopened Central line tunnels hid a secret aircraft-parts factory during WWII.",
    "Wanstead Park": "Despite its name the station is neither in Wanstead nor by Wanstead Park: it sits in Forest Gate beside the open grassland of Wanstead Flats.",
    "Wapping": "The station's entrance occupies the northern shaft of Brunel's Thames Tunnel, the first tunnel known to have been driven successfully beneath a navigable river, which opened to pedestrians in 1843.",
    "Warren Street": "Its Victoria line platforms carry a maze tile motif by the Crosby/Fletcher/Forbes design partnership, a visual pun on the 'warren' in the station's name.",
    "Warwick Avenue": "It serves Little Venice, the canal pool often linked to the poet Robert Browning, who lived nearby; the avenue itself is said to be named after Jane Warwick of Warwick Hall near Carlisle.",
    "Waterloo": "Waterloo is served by the Waterloo & City line, the little shuttle Londoners nickname 'the Drain'.",
    "Watford": "This Metropolitan line terminus sits in the Cassiobury area close to the park, about a mile from the town centre it was once marketed to reach as part of Metro-land.",
    "Watford High Street": "The station opened in 1862 on the branch from Watford Junction to Rickmansworth and today serves as the junction with the line up to the town centre.",
    "Watford Junction": "It is the rail gateway to the Warner Bros. Studio Tour, with electric shuttle buses running the roughly 15 minutes to the Making of Harry Potter sets at nearby Leavesden.",
    "Wembley Central": "Linked to Wembley Stadium by the White Horse Bridge, it was renamed from 'Wembley for Sudbury' to Wembley Central in 1948, the year London hosted the Olympic Games.",
    "Wembley Park": "Wembley Park is the stop for Wembley Stadium.",
    "West Acton": "Its Grade II listed building is the only station completed to the original design of Australian-born GWR architect Brian Lewis, opened in 1940 as part of the New Works Programme.",
    "West Brompton": "The station sits beside the Victorian Brompton Cemetery, one of London's 'Magnificent Seven', and close to Chelsea FC's Stamford Bridge stadium.",
    "West Croydon": "The station stands on the site of the terminal basin of the old Croydon Canal, which closed in 1836 so that the London and Croydon Railway could reuse much of its route.",
    "West Drayton": "The world's first commercial electric telegraph line ran beside the track here, opening in 1839 along the Great Western Railway from Paddington to West Drayton.",
    "West Ealing": "The station opened in 1871 as Castle Hill, was later renamed Castle Hill, Ealing Dean, and finally became West Ealing in 1899.",
    "West Finchley": "The station opened in 1933 fitted with second-hand materials from closed northern railways, and its footbridge is said to have come from a Yorkshire colliery line, though which station it came from is disputed.",
    "West Ham": "Comprehensively rebuilt for the 1999 Jubilee line extension to a design evoking Charles Holden's 1930s work, it was by far the cheapest of the new stations on that line.",
    "West Hampstead": "It is one of three separate stations strung along West End Lane within about 200 metres, serving the Jubilee line, the Overground and Thameslink.",
    "West Harrow": "It opened in 1913 as a wooden halt after residents of the growing Bessborough Estate pressed the Metropolitan Railway to add a stop on its line towards Uxbridge.",
    "West India Quay": "Beside the station stands a Grade I listed Georgian sugar warehouse of 1802, now home to the Museum of London Docklands.",
    "West Kensington": "It opened on the District Railway in 1874 as 'North End (Fulham)' and was renamed West Kensington in 1877, with its entrance later rebuilt to a Charles Holden design.",
    "West Ruislip": "It is the western terminus of the Central line, where the Underground shares the site with Chiltern Railways trains running out towards Buckinghamshire.",
    "West Silvertown": "Silvertown takes its name from Samuel Winkworth Silver's india rubber, gutta-percha and telegraph works, which from 1852 grew to employ much of the local population.",
    "Westbourne Park": "It has an eastbound platform exit onto Tavistock Crescent that opens during the Notting Hill Carnival to move large crowds out of the station quickly.",
    "Westferry": "There was never a west ferry: the name is a back-formation by the DLR from Westferry Road, one of two roads that once led to a Greenwich watermen's ferry at the southern tip of the Isle of Dogs.",
    "Westminster": "Westminster's deep station box sits beneath Portcullis House, right by Parliament and Big Ben.",
    "White City": "It is named after the gleaming white-clad buildings of the 1908 Franco-British Exhibition, whose stadium hosted that year's Olympic Games.",
    "White Hart Lane": "Both the station and Tottenham Hotspur's old ground took their popular name from the local road and the historic White Hart public house rather than from one another.",
    "Whitechapel": "Its Whitechapel Road entrance dates from the 1876 railway station, and the nearby Royal London Hospital cared for Joseph Merrick, the 'Elephant Man', until his death in 1890.",
    "Willesden Green": "Its cream faience station buildings, dating from a 1925 rebuild by Metropolitan Railway architect C. W. Clark and retaining original mosaic tiling, helped earn the station its Grade II listing.",
    "Willesden Junction": "In the late nineteenth century its maze of platforms and passages earned it the nickname 'Bewildering Junction', and it sits beside Old Oak Common, where HS2's new interchange is being built.",
    "Wimbledon": "Wimbledon, a District line terminus, is home to the tennis championships.",
    "Wimbledon Park": "It is one of three District line stops serving the All England Lawn Tennis Club, about a 25 minute walk from the Wimbledon Championships courts.",
    "Wood Green": "A Charles Holden design from the 1932 Piccadilly line Cockfosters extension, it is the closest Tube station to Alexandra Palace, where the BBC began its television service in 1936.",
    "Wood Lane": "Opened in 2008 to serve Westfield London, it was the first wholly new station built on an existing Tube line in over 70 years, the previous one being Elm Park in 1935.",
    "Wood Street": "It sits in Walthamstow, where the designer William Morris grew up, his family home at Water House in nearby Lloyd Park now housing the William Morris Gallery.",
    "Woodford": "Winston Churchill represented this constituency as an MP for around 40 years, and a bronze statue of him by David McFall, unveiled in 1959, stands on nearby Woodford Green.",
    "Woodgrange Park": "The station takes its name from the Woodgrange estate, a planned suburb of several hundred homes laid out from the late 1870s by the prolific developer Cameron Corbett.",
    "Woodside Park": "This country-style station keeps a Victorian VR postbox set into its front wall and lies beside the Dollis Brook in leafy Barnet.",
    "Woolwich": "The Elizabeth line station was built on part of the former Royal Arsenal, where munitions workers founded the football club in 1886 that became Arsenal FC.",
    "Woolwich Arsenal": "Arsenal FC began nearby in 1886 as Dial Square, named after a workshop in the Royal Arsenal where its munitions-worker founders were employed.",
}
"""Display-name -> one-sentence fun fact. Matched via ``normalise_name``."""
